---
# tasks file for zookeeper

- block:
  - name: install zookeeperd
    apt:
      name: zookeeperd
      cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
      install_recommends: false
      state: present
      update_cache: true

  - name: configure zookeeper service
    service:
      name: zookeeper
      enabled: "{{ zookeeper_enabled }}"
      state: "{{ zookeeper_state }}"

  become: true
  become_method: sudo
  tags:
    - zookeeper
